version: 2
updates:
  # Enable version updates for Maven
  - package-ecosystem: "maven"
    directory: "/backend"
    target-branch: "develop"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    open-pull-requests-limit: 10
    reviewers:
      - "ChHsiching"
    assignees:
      - "ChHsiching"
    commit-message:
      prefix: "📦"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "develop"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    reviewers:
      - "ChHsiching"
    assignees:
      - "ChHsiching"
    commit-message:
      prefix: "🔧"
      include: "scope"