name: Deploy Spring Boot (1Panel container)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出仓库
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. 设置 JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # 3. 构建 backend 模块
      - name: Build with Maven
        working-directory: backend
        run: mvn clean package -DskipTests

      # 4. 准备 SSH key
      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > ./deploy_key
          chmod 600 ./deploy_key
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      # 5. 上传 JAR 到服务器
      - name: Upload jar to server
        run: |
          scp -i ./deploy_key backend/target/backend-0.0.1-SNAPSHOT.jar \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/root/order-management-system/backend/

      # 6. 重启容器
      - name: Restart container
        run: |
          ssh -i ./deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<'EOF'
            docker restart order-backend
          EOF