name: Deploy Spring Boot (1Panel container)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SERVER_SSH_KEY }}" > ./deploy_key
          chmod 600 ./deploy_key
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload jar to server
        run: |
          scp -i ./deploy_key target/backend-0.0.1-SNAPSHOT.jar \
            ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/root/order-management-system/backend/

      - name: Restart container
        run: |
          ssh -i ./deploy_key ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<'EOF'
